services:
  vllm-qwen38-27b-autoround-int4:
    # image: vllm/vllm-openai:v0.22.0
    image: vllm/vllm-openai:v0.27.1
    container_name: vllm-qwen38-27b-autoround-int4
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - /home/app/models/Avuja/Qwen3.8-27B-int4-AutoRound:/models/Qwen3.8-27B-int4-AutoRound:ro
      - /home/app/cache/vllm/torch_compile:/root/.cache/vllm/torch_compile_cache
      - /home/app/cache/vllm/triton:/root/.triton/cache
      - /home/app/models/froggeric/Qwen-Fixed-Chat-Templates/chat_template.jinja:/etc/qwen-froggeric-chat-template.jinja:ro
    environment:
      - NCCL_CUMEM_ENABLE=0
      - NCCL_P2P_DISABLE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - OMP_NUM_THREADS=1
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:512
      - VLLM_NO_USAGE_STATS=1
      - VLLM_USE_FLASHINFER_SAMPLER=1
      - VLLM_WORKER_MULTIPROC_METHOD=spawn
      - CUDA_VISIBLE_DEVICES
    shm_size: "16gb"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    entrypoint: ["vllm", "serve"]
    command:
      - --model=/models/Qwen3.8-27B-int4-AutoRound
      - --served-model-name=qwen3.8-27b
      - --dtype=bfloat16
      - --max-num-seqs=2
      - --trust-remote-code
      - --max-model-len=262144
      - --enable-prefix-caching
      - --enable-chunked-prefill
      - --reasoning-parser=qwen3
      - --tensor-parallel-size=2
      - --quantization=auto_round
      - --kv-cache-dtype=fp8_e4m3
      - --enable-auto-tool-choice
      - --pipeline-parallel-size=1
      - --disable-custom-all-reduce
      - --gpu-memory-utilization=0.90
      - --max-num-batched-tokens=8192
      - --tool-call-parser=qwen3_coder
      - --chat-template=/etc/qwen-froggeric-chat-template.jinja
      - '--default-chat-template-kwargs={"enable_thinking": false}'
      - '--speculative-config={"method":"mtp","num_speculative_tokens":3}'
      - '--override-generation-config={"temperature":0.7,"top_p":0.80,"top_k":20,"min_p":0.0,"repetition_penalty":1.0,"presence_penalty":1.5}'
      - --host=0.0.0.0
      - --port=8000
