services:
  llama-cpp:
    # image: ghcr.io/ggml-org/llama.cpp:server-cuda-b9246
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    # image: ghcr.io/ggml-org/llama.cpp:server-cuda-b10092
    container_name: llama-cpp-laguna-xs-2.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /models/poolside/Laguna-XS-2.1-GGUF:/models:ro
    command: >-
      --host 0.0.0.0
      --port 8080
      -m /models/Laguna-XS-2.1-Q4_K_M.gguf
      --alias laguna-xs-2.1
      -c ${CTX_SIZE:-524288}
      -b ${BATCH_SIZE:-4096}
      -ub ${UBATCH_SIZE:-512}
      -ngl 99
      -fa on
      --cache-type-k ${KV_TYPE:-q4_0}
      --cache-type-v ${KV_TYPE:-q4_0}
      -np ${NP:-2}
      --jinja
      --reasoning ${REASONING:-off}
      --reasoning-format ${REASONING_FORMAT:-deepseek}
      --temp ${TEMP:-${TEMPERATURE:-0.6}}
      --top-p ${TOP_P:-0.95}
      --top-k ${TOP_K:-20}
      --min-p ${MIN_P:-0.0}
      --repeat-penalty ${REPEAT_PENALTY:-1.0}
      --split-mode layer

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
